server:
  port: 8081
spring:
  datasource:
    username: root
    password: 9NXhFz8p*^
    url: jdbc:mysql://121.40.73.144:3306/WeLinkUser?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource    #切换数据源，如果不写，会使用默认的
    druid:
      # 以下是DuriDataSource的基本配置，如果不写，使用springboot默认的
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接.
      minEvictableIdleTimeMillis: 300000  #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false  #获取连接时执行检测，建议关闭，影响性能
      testOnReturn: false  #归还连接时执行检测，建议关闭，影响性能
      poolPreparedStatements: true  #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大,
        # oracle建议开启，mysql下建议关闭
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      maxPoolPreparedStatementPerConnectionSize: 20   #开启poolPreparedStatements后生效
      useGlobalDataSourceStat: true
      #通过connectProperties属性来打开mergeSql功能;慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
#    host: 121.40.73.144
#    password: bD0&pB5?bU5&iL3_
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1m
    database: 0
    host: 127.0.0.1
    password: 367635984
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
